
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Oct 02 17:46:48 CST 2024
//----------------------------------------------------

package act_4_demo_cup;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CADENA = 15;
  public static final int PUNTO = 6;
  public static final int COMENTARIO_BLOQUE = 14;
  public static final int PUNTO_COMA = 5;
  public static final int TRUE = 3;
  public static final int NUMERO_ENTERO = 10;
  public static final int OPERADOR_ASIGNACION = 7;
  public static final int COMENTARIO_LINEA = 13;
  public static final int EOF = 0;
  public static final int DECLARADOR = 9;
  public static final int FALSE = 4;
  public static final int NAMESPACE = 2;
  public static final int NUMERO_FLOTANTE = 11;
  public static final int error = 1;
  public static final int IDENTIFICADOR_INVALIDO = 12;
  public static final int IDENTIFICADOR = 8;
}

