
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Oct 02 20:51:36 CST 2024
//----------------------------------------------------

package act_5_aritmetica;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int IDENTIFICADOR_INVALIDO = 32;
  public static final int PARENTESIS_CIERRE = 7;
  public static final int OPERADOR_MULTIPLICACION = 18;
  public static final int OPERADOR_LOGICO_OR = 22;
  public static final int DECLARADOR = 29;
  public static final int COMENTARIO_LINEA = 33;
  public static final int IDENTIFICADOR = 28;
  public static final int OPERADOR_DIVISION = 19;
  public static final int CORCHETE_CIERRE = 9;
  public static final int OPERADOR_DESIGUALDAD = 15;
  public static final int OPERADOR_IDENTIDAD = 14;
  public static final int PUNTO_COMA = 10;
  public static final int EOF = 0;
  public static final int NUMERO_FLOTANTE = 31;
  public static final int CORCHETE_APERTURA = 8;
  public static final int TRUE = 2;
  public static final int error = 1;
  public static final int CADENA = 35;
  public static final int OPERADOR_MODULO = 20;
  public static final int MENOR = 25;
  public static final int OPERADOR_SUMA = 16;
  public static final int OPERADOR_LOGICO_NOT = 23;
  public static final int OPERADOR_LOGICO_AND = 21;
  public static final int MAYOR = 24;
  public static final int PUNTO = 11;
  public static final int OPERADOR_IGUALDAD = 13;
  public static final int LLAVE_APERTURA = 4;
  public static final int OPERADOR_RESTA = 17;
  public static final int MAYOR_IGUAL = 26;
  public static final int LLAVE_CIERRE = 5;
  public static final int COMENTARIO_BLOQUE = 34;
  public static final int OPERADOR_ASIGNACION = 12;
  public static final int PARENTESIS_APERTURA = 6;
  public static final int MENOR_IGUAL = 27;
  public static final int FALSE = 3;
  public static final int NUMERO_ENTERO = 30;
}

