
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Oct 25 12:17:14 CST 2024
//----------------------------------------------------

package act_8_sintactico;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int FUNCTION = 10;
  public static final int PARENTESIS_CIERRE = 35;
  public static final int CONST = 12;
  public static final int OPERADOR_MULTIPLICACION = 48;
  public static final int NAMESPACE = 2;
  public static final int OPERADOR_LOGICO_OR = 53;
  public static final int CASE = 24;
  public static final int DOS_PUNTOS = 40;
  public static final int PRIVATE = 6;
  public static final int BARRA_INVERSA = 50;
  public static final int COMENTARIO_LINEA = 65;
  public static final int ECHO = 27;
  public static final int FOR = 20;
  public static final int STDIN = 31;
  public static final int STATIC = 8;
  public static final int CONSTANTE = 61;
  public static final int IDENTIFICADOR = 59;
  public static final int OPERADOR_DIVISION = 49;
  public static final int ELSEIF = 18;
  public static final int CORCHETE_CIERRE = 37;
  public static final int OPERADOR_DESIGUALDAD = 45;
  public static final int OPERADOR_IDENTIDAD = 44;
  public static final int USE = 3;
  public static final int OR = 14;
  public static final int TRIM = 29;
  public static final int CLASES = 4;
  public static final int IF = 17;
  public static final int PUNTO_COMA = 38;
  public static final int NUMERO_FLOTANTE = 63;
  public static final int EOF = 0;
  public static final int CORCHETE_APERTURA = 36;
  public static final int TRUE = 15;
  public static final int error = 1;
  public static final int COMA = 39;
  public static final int CADENA = 67;
  public static final int MENOR = 56;
  public static final int OPERADOR_MODULO = 51;
  public static final int OPERADOR_SUMA = 46;
  public static final int BREAK = 25;
  public static final int VOID = 13;
  public static final int OPERADOR_LOGICO_NOT = 54;
  public static final int OPERADOR_LOGICO_AND = 52;
  public static final int SWITCH = 23;
  public static final int MAYOR = 55;
  public static final int FGETS = 30;
  public static final int ELSE = 19;
  public static final int PUNTO = 41;
  public static final int PROTECTED = 7;
  public static final int VARIABLE = 60;
  public static final int OPERADOR_IGUALDAD = 43;
  public static final int LLAVE_APERTURA = 32;
  public static final int OPERADOR_RESTA = 47;
  public static final int FINAL = 9;
  public static final int WHILE = 21;
  public static final int MAYOR_IGUAL = 57;
  public static final int DEFAULT = 26;
  public static final int PUBLIC = 5;
  public static final int LLAVE_CIERRE = 33;
  public static final int CONSTRUCT = 11;
  public static final int COMENTARIO_BLOQUE = 66;
  public static final int OPERADOR_ASIGNACION = 42;
  public static final int PARENTESIS_APERTURA = 34;
  public static final int MENOR_IGUAL = 58;
  public static final int FALSE = 16;
  public static final int NUMERO_ENTERO = 62;
  public static final int VARIABLE_INVALIDO = 64;
  public static final int PRINT = 28;
  public static final int DO = 22;
}

