
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Oct 06 16:07:34 CST 2024
//----------------------------------------------------

package act_6_control;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PARENTESIS_CIERRE = 13;
  public static final int OPERADOR_MULTIPLICACION = 24;
  public static final int OPERADOR_LOGICO_OR = 28;
  public static final int COMENTARIO_LINEA = 39;
  public static final int FOR = 8;
  public static final int IDENTIFICADOR = 34;
  public static final int OPERADOR_DIVISION = 25;
  public static final int ELSEIF = 6;
  public static final int CORCHETE_CIERRE = 15;
  public static final int OPERADOR_DESIGUALDAD = 21;
  public static final int OPERADOR_IDENTIDAD = 20;
  public static final int OR = 2;
  public static final int IF = 5;
  public static final int PUNTO_COMA = 16;
  public static final int NUMERO_FLOTANTE = 37;
  public static final int EOF = 0;
  public static final int CORCHETE_APERTURA = 14;
  public static final int TRUE = 3;
  public static final int error = 1;
  public static final int CADENA = 41;
  public static final int OPERADOR_MODULO = 26;
  public static final int MENOR = 31;
  public static final int OPERADOR_SUMA = 22;
  public static final int OPERADOR_LOGICO_NOT = 29;
  public static final int OPERADOR_LOGICO_AND = 27;
  public static final int MAYOR = 30;
  public static final int ELSE = 7;
  public static final int PUNTO = 17;
  public static final int VARIABLE = 35;
  public static final int OPERADOR_IGUALDAD = 19;
  public static final int LLAVE_APERTURA = 10;
  public static final int OPERADOR_RESTA = 23;
  public static final int WHILE = 9;
  public static final int MAYOR_IGUAL = 32;
  public static final int LLAVE_CIERRE = 11;
  public static final int COMENTARIO_BLOQUE = 40;
  public static final int OPERADOR_ASIGNACION = 18;
  public static final int PARENTESIS_APERTURA = 12;
  public static final int MENOR_IGUAL = 33;
  public static final int FALSE = 4;
  public static final int NUMERO_ENTERO = 36;
  public static final int VARIABLE_INVALIDO = 38;
}

