
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Oct 14 00:06:09 CST 2024
//----------------------------------------------------

package act_7_clases;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int FUNCTION = 6;
  public static final int PARENTESIS_CIERRE = 20;
  public static final int NAMESPACE = 2;
  public static final int OPERADOR_MULTIPLICACION = 33;
  public static final int OPERADOR_LOGICO_OR = 38;
  public static final int DOS_PUNTOS = 25;
  public static final int BARRA_INVERSA = 35;
  public static final int COMENTARIO_LINEA = 49;
  public static final int FOR = 15;
  public static final int IDENTIFICADOR = 44;
  public static final int OPERADOR_DIVISION = 34;
  public static final int ELSEIF = 13;
  public static final int CORCHETE_CIERRE = 22;
  public static final int OPERADOR_DESIGUALDAD = 30;
  public static final int OPERADOR_IDENTIDAD = 29;
  public static final int USE = 3;
  public static final int OR = 9;
  public static final int CLASES = 4;
  public static final int IF = 12;
  public static final int PUNTO_COMA = 23;
  public static final int NUMERO_FLOTANTE = 47;
  public static final int EOF = 0;
  public static final int CORCHETE_APERTURA = 21;
  public static final int TRUE = 10;
  public static final int error = 1;
  public static final int COMA = 24;
  public static final int CADENA = 51;
  public static final int MENOR = 41;
  public static final int OPERADOR_MODULO = 36;
  public static final int OPERADOR_SUMA = 31;
  public static final int VOID = 8;
  public static final int OPERADOR_LOGICO_NOT = 39;
  public static final int OPERADOR_LOGICO_AND = 37;
  public static final int MAYOR = 40;
  public static final int ELSE = 14;
  public static final int PUNTO = 26;
  public static final int VARIABLE = 45;
  public static final int OPERADOR_IGUALDAD = 28;
  public static final int LLAVE_APERTURA = 17;
  public static final int OPERADOR_RESTA = 32;
  public static final int WHILE = 16;
  public static final int MAYOR_IGUAL = 42;
  public static final int PUBLIC = 5;
  public static final int LLAVE_CIERRE = 18;
  public static final int CONSTRUCT = 7;
  public static final int COMENTARIO_BLOQUE = 50;
  public static final int OPERADOR_ASIGNACION = 27;
  public static final int PARENTESIS_APERTURA = 19;
  public static final int MENOR_IGUAL = 43;
  public static final int FALSE = 11;
  public static final int NUMERO_ENTERO = 46;
  public static final int VARIABLE_INVALIDO = 48;
}

